### PR TITLE
Fixes #181: Listing bucket with a prefix can give wrong results

### LINKED ISSUE #181: Listing bucket with a prefix can give wrong results
Listing a bucket with e.g. "3330/0", "33309/0" and prefix "3330/" will return both keys.
Root cause is the changes introduced in commit 75a5e674eba2bddbf4929454ed4c19a7ddfdd6df
I will submit a PR with a fix

### PR DESCRIPTION
**Pull request by 412b**
also includes changes to be able to run javadoc on java 11

## Description
Fixes normalization of the prefix

## Related Issue
Fixes #181 

## Tasks
- [x] I have signed the [CLA](http://adobe.github.io/cla.html).
- [x] I have written tests and verified that they fail without my change.

### CODE REVIEW

**Comment by timoe** [comment]
thanks for your contribution. We'll merge it once we got Travis CI build passing.

**Comment by ChaithanyaGK** [comment]
retest

**Comment by 412b** [comment]
hi @timoe, is there any success with Travis CI so far?

**Comment by timoe** [comment]
right, we fixed travis build. sorry for not coming back to this.

can you please do a rebase+force-push to trigger build.

Thanks

**Comment by 412b** [comment]
@timoe, looks good/green :)

**Pull request merged**
