### PR TITLE
Fixed some typos

### PR DESCRIPTION
**Pull request by NinjaCoderDev**
Little changes in the readme.md , contributing.md and code_of_conduct.md

### CODE REVIEW

**Comment by timoe** [comment]
thanks for your contribution. We'll merge it once we got Travis CI build passing.

**Comment by NinjaCoderDev** [comment]
All commits squashed into one .

**Comment by timoe** [comment]
any updates here @NinjaCoderDev? Please revert your changes in code_of_conduct.md, we'll merge afterwards.

**Comment by timoe** [comment]
closed due to inactivity

**Pull request closed without merging**
