### PR TITLE
provide a banner for the logs

### PR DESCRIPTION
**Pull request by jens-meiss**
banner added to override the spring default banner, which provides a better service recognition in the logs

* http://www.network-science.de/ascii/
* Font: epic
* Reflection: none
* Adjustment: center
* Stretch: no
* Width: 80

### CODE REVIEW

**Comment by agudian** [comment]
Love it, thanks! It's a bit large, though... how about removing the Adobe and make it fit in one line? You can also write S3Mock without the space in between.

And the license-maven-plugin needs to be configured to ignore that file...

**Comment by jens-meiss** [comment]
done :)

**Comment by agudian** [comment]
oh, now it says "S3MOCKS"... please remove the trailing S. :)

And I saw that in the Docker output further below in the log, the leading whitespaces are removed... Do you think you can add maybe something in the first column? Perhaps draw an ASCII art frame around it?

**Comment by jens-meiss** [comment]
ok, i centered the text again, since i'm using the ascii generator of http://www.network-science.de/ascii/ there is no way to set a border or something, we have banners like this in all of our services and using it almost just to have a indication where a service startup appears in the logs

i you want further changes of a banner maybe just merge this pull request and make the changes by yourselfe :)

**Comment by agudian** [comment]
@jens-meiss the change has been released. Thanks again for adding this! 👍

**Pull request merged**
