### PR TITLE
accept object tagging via PutObject requests

### PR DESCRIPTION
**Pull request by raptros**
## Description
* add extraction of tags from request to putObject() and putObjectEncrypted()
* add integration test to show it working

## Related Issue
should handle #142 

## Tasks
- [x] I have signed the [CLA](http://adobe.github.io/cla.html). (signed for Indeed).
- [x] I have written tests and verified that they fail without my change.

### CODE REVIEW

**Comment by raptros** [comment]
Thank you very much! Glad to be able to help. When do you think a new release might be made, by the way?

**Comment by agudian** [comment]
I was about to wait for #150, which is being worked on right now. Should be done by tomorrow. Is that okay? Otherwise I can spin the release now as well.

**Comment by raptros** [comment]
I can wait for a day or so, thank you.

**Comment by agudian** [comment]
Release is done. `2.1.8` should be available on Docker Hub already, and will show up on Maven Central soon.

**Comment by raptros** [comment]
Great, thank you very much!

**Pull request merged**
