### PR TITLE
Allow clients to customize s3mock server TLS certificate

### PR DESCRIPTION
**Pull request by vlsi**
This enables to use of a regular S3 client with full TLS verification.

## Related Issue

https://github.com/adobe/S3Mock/issues/230

## Tasks

- [x] I have signed the [CLA](http://adobe.github.io/cla.html).
- [x] I have written tests and verified that they fail without my change.

### CODE REVIEW

**Comment by vlsi** [comment]
@agudian , would you please review?

**Comment by vlsi** [comment]
@agudian , I'm sorry I give up.

I can't build the project locally (see https://github.com/adobe/S3Mock/issues/235 ), and the build error messages like the following are completely insane.

```
[WARNING] Missing header in: /home/travis/build/adobe/S3Mock/testsupport/junit5/src/test/java/com/adobe/testing/s3mock/junit5/sdk1/CustomCertificateTest.java
```

I do understand the necessity of the legal stuff, however, ill error messages completely demotivating, and I don't want to spend my time fighting with Checkstyle / Maven.
It looks like I've spent half a day adding a trivial getters + test to the project, and even now the Travis build fails. I will no longer update the PR. I don't think I want to contribute more taking into account the barrier is so high.

It would be great if you could remove license-maven-plugin / Checkstyle from your build completely.
There are modern tools that provide human-readable error messages and even automatic error correction: https://github.com/diffplug/spotless, https://github.com/autostyle/autostyle, https://github.com/pinterest/ktlint

Please feel free to reject my PRs.

Have a nice day.

**Comment by agudian** [comment]
@vlsi So sorry to hear that, fighting with a bad developer experience like you did is always a bummer and I totally get it. That building locally doesn't work for you is bad enough, and that the checkstyle warnings don't help is similarly bad. Add to that the lack of response from me (was on vacation). So I understand your frustration, and thanks for your effort anyway.

If you still have a need for your contributions here, let me know and I'll fix up the PR (I think the license header should contain `2017-2020` instead of `2020`, at least according to the checkstyle rule).

**Comment by vlsi** [comment]
> was on vacation

Vacation is great.

>I think the license header should contain 2017-2020 instead of 2020, at least according to the checkstyle rule

Well, I can try adding `2017-2020`, however, it does sound weird. Technically speaking, `CustomCertificateTest.java` was created in 2020, so adding a copyright claim `since 2017` is not right. The file did not exist in 2017. It would be a false copyright claim.

**Comment by vlsi** [comment]
Ok, `2017-2020` for the newly added file pleases Checkstyle, however, technically speaking the proper header should be just 2020.

**Comment by agudian** [comment]
lawyers, right? 🤷 

Thanks a lot! I'll add you to the contributors list and run a release build.

**Pull request merged**
