### PR TITLE
Fixes #112: continuation token and start after

### LINKED ISSUE #112: Continuation token invalidated by delete.
In case the bucket has more than a 1000 objects and I would like to delete them, I list the objects batchwise using nextMarker(v1)/nextContinuationToken(v2). So I request a batch,  delete the batch, request the next batch using the next marker/token, delete it and so on.

The problem I face with the adobe/S3Mock is that the continuation token specifies the offset into the buckets current object list as seen [here](https://github.com/adobe/S3Mock/blob/master/server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java#L360). Obviously if some items before the marker are deleted, the itemstoskip mapped to the marker/continuation token is invalidated.

A correct implementation should return items starting next after the marker in S3 sort oder.
See [marker](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html) and [continuation token](https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html).

I hacked a solution that works for me [here](https://github.com/sparlampe/S3Mock/commit/e2935e2eff5cc2fcc357f1d8f059343752ee76d5). If a solution based on sorting and mapping the token to a key would be fine, I would be able to submit a PR.

### PR DESCRIPTION
**Pull request by 412b**
## Description
continuation token is now mapped to key in order to be able to get correct elements in case of removals/uploads.
start after was also fixed to work properly (esp. in case of missing key)
also continuation token and start after now share processing and follow Amazon's "This parameter is valid only in your first request. If the response is truncated, you can specify this parameter along with the continuation-token parameter, and then Amazon S3 ignores this parameter."
## Related Issue
Fixes #112: continuation token and start after

## Tasks

- [x] I have signed the [CLA](http://adobe.github.io/cla.html).
- [x] I have written tests and verified that they fail without my change.

### CODE REVIEW

**Comment by 412b** [comment]
@agudian how broad should the test coverage be here?

**Comment by agudian** [comment]
@412b: sorry, I dropped the ball on this. I'd say the tests should recreate the assertions that you described above, to make sure that we don't accidentally break this. An *IT is fine for that.

**Comment by 412b** [comment]
@agudian no worries :) I've adjusted the test a bit to have `start-after` in the test as well.
unfortunately it turned out that V1 doesn't support `marker`, but that's out of the scope of this PR.

**Comment by 412b** [comment]
@agudian also it looks like I will have to rebase due to changes related to `encoding-type`...

**Comment by 412b** [comment]
@agudian ping on this one

**Comment by agudian** [comment]
Sorry for all the delay, we’re a bit swamped right now. But we’ll see that we find some time this week.

**Pull request merged**
