### PR TITLE
Fix getS3Objects for root directory.

### PR DESCRIPTION
**Pull request by mattelacchiato**
Empty prefix should have the same meaning as null prefix.

### CODE REVIEW

**Comment by agudian** [comment]
Great, thank you! Do you need a release for that right away or is there more coming up? 🙂

**Comment by mattelacchiato** [comment]
I don't know of anything more to come :)

**Comment by agudian** [comment]
Release is done 👍 1.0.4 is on Dockerhub and the Java binaries will show up on Maven central shortly.
Out of curiosity: are you using the Docker image or the jar with the JUnit `Rule`?

**Comment by mattelacchiato** [comment]
We're using the jar directly (`com.adobe.testing.s3mock.S3MockApplication.start`). Since our codebase is scala, we don't use JUnit...

**Pull request merged**
