### PR TITLE
Multipart md5 hash calculation is incorrect #66

### PR DESCRIPTION
**Pull request by mattelacchiato**
## Description
Implementation of special etag calculation.
See https://stackoverflow.com/questions/12186993/what-is-the-algorithm-to-compute-the-amazon-s3-etag-for-a-file-larger-than-5gb

## Related Issue
#66 

## Tasks

- [x] I have signed the [CLA](http://adobe.github.io/cla.html).
- [x] I have written tests and verified that they fail without my change.

### CODE REVIEW

**Comment by timoe** [comment]
Thanks for the contribution @mattelacchiato. I'll have a look

**Comment by magro** [comment]
@timoe Because my colleage @mattelacchiato is on vacation now I'm continuing here... While the test looks good here, integrating this new version in our application shows failures:
```
java.nio.BufferOverflowException: null
        at java.nio.Buffer.nextPutIndex(Buffer.java:521)
        at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
        at com.adobe.testing.s3mock.util.AwsChunkDecodingInputStream.readUntil(AwsChunkDecodingInputStream.java:115)
        at com.adobe.testing.s3mock.util.AwsChunkDecodingInputStream.read(AwsChunkDecodingInputStream.java:72)
        at java.io.InputStream.read(InputStream.java:170)
        at java.io.InputStream.skip(InputStream.java:224)
        at com.adobe.testing.s3mock.domain.FileStore.copyPart(FileStore.java:957)
        at com.adobe.testing.s3mock.domain.FileStore.copyPart(FileStore.java:942)
```

While with `AmazonClientUploadIT.multipartCopy` v4 signing is not used (because the related header is set to "UNSIGNED-PAYLOAD" - actually not sure why and how I could change this), in our application v4 signing is enabled/used. This leads to the usage of `AwsChunkDecodingInputStream` (which can be seen in the stacktrace above) and AFAICS is the reason for the issue I'm seeing.
Because `FileStore.copyPart` reads from a `File` directly, using `AwsChunkDecodingInputStream` makes absolutely no sense IMO. Therefore I propose to simply remove this here (in `FileStore.copyPart`).

WDYT?

**Comment by magro** [comment]
I've just added a commit which shows my proposed change.

**Comment by timoe** [comment]
Right, AwsChunkDecodingInputStream is something that seems to make problems also when using S3 operation from AWS CLI - see issue #85. 

I'll have a look as soon as I'm able to

**Comment by magro** [comment]
@timoe AFAICS in #85 there's in fact the servlet input stream used, i.e. it _could_ in fact be a chunked input. My point however is, that `FileStore.copyPart` reads from the stored _file_, which I'd expect never to be stored in some chunked encoding. Therefore, for reading the source file IMO it simply makes no sense to use `AwsChunkDecodingInputStream` here.

**Comment by timoe** [comment]
Thanks again, I'll do a release tomorrow.

**Comment by timoe** [comment]
S3Mock 2.0.10 was released

**Comment by mattelacchiato** [comment]
Yeah, thank you!

**Pull request merged**
